services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patientsynchealth-api
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=PatientSyncHealth;Username=postgres;Password=YourStrong@Passw0rd
    depends_on:
      db:
        condition: service_healthy
    networks:
      - patientsynchealth-network

  db:
    image: postgres:18
    container_name: patientsynchealth-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=PatientSyncHealth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PatientSyncHealth"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - patientsynchealth-network

volumes:
  postgres-data:

networks:
  patientsynchealth-network:
    driver: bridge
